version: '3.9'

services:
  reverse-proxy:
    build: .
    container_name: reverse-proxy
    hostname: reverse-proxy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
