name: "lint"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile
        
      - name: Check docker-compose
        run: docker-compose -f docker-compose.yml config
